### ISSUE TITLE
i believe it needs to be updated to python 3.12 (but im not sure im really a noob)

### ISSUE THREAD

**Issue by mrbeatbox** [jtpotato/autocut#1]
I got this error
if i understand correctly its cuz i have 3.12 as python version which is odd. anyways hopefully you can find a solution for this
```
C:\Users\enfaz>autocut setup
Upgrade complete, installed `auto-editor` and `openai-whisper`.
Error: Command failed: pip install --upgrade git+https://github.com/openai/whisper.git
  Running command git clone --filter=blob:none --quiet https://github.com/openai/whisper.git 'C:\Users\enfaz\AppData\Local\Temp\pip-req-build-ng9bm7sj'
  error: subprocess-exited-with-error

  Getting requirements to build wheel did not run successfully.
  exit code: 1

  [21 lines of output]
  Traceback (most recent call last):
    File "C:\Users\enfaz\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\enfaz\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\enfaz\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\enfaz\AppData\Local\Temp\pip-build-env-u5badrod\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\enfaz\AppData\Local\Temp\pip-build-env-u5badrod\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
      self.run_setup()
    File "C:\Users\enfaz\AppData\Local\Temp\pip-build-env-u5badrod\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
      super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
    File "C:\Users\enfaz\AppData\Local\Temp\pip-build-env-u5badrod\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
      exec(code, locals())
    File "<string>", line 51, in <module>
    File "<string>", line 48, in _guard_py_ver
  RuntimeError: Cannot install on Python version 3.12.0; only versions >=3.8,<3.12 are supported.
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'pip install --upgrade git+https://github.com/openai/whisper.git'
}

C:\Users\enfaz>
```

**Comment by jtpotato** [comment]
looks like OpenAI's Whisper won't work on 3.12. Seeing that it released a few days ago, I'm not that surprised
Maybe try with Python 3.11.6??

**Comment by jtpotato** [comment]
I'll be closing the issue for now
If you're still having problems, feel free to reopen :)
